/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_android_video_worker_EFEditorWorker */

#ifndef _Included_com_android_video_worker_EFEditorWorker
#define _Included_com_android_video_worker_EFEditorWorker
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_android_video_worker_EFEditorWorker
 * Method:    createEditorWorker
 * Signature: (Ljava/lang/Object;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_android_video_worker_EFEditorWorker_createEditorWorker
  (JNIEnv *, jobject, jobject, jstring, jstring);

/*
 * Class:     com_android_video_worker_EFEditorWorker
 * Method:    updateTouchEvent
 * Signature: (IFF)Z
 */
JNIEXPORT jboolean JNICALL Java_com_android_video_worker_EFEditorWorker_updateTouchEvent
  (JNIEnv *, jobject, jint, jfloat, jfloat);

/*
 * Class:     com_android_video_worker_EFEditorWorker
 * Method:    destoryEditorWorker
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_android_video_worker_EFEditorWorker_destoryEditorWorker
  (JNIEnv *, jobject);

/*
 * Class:     com_android_video_worker_EFEditorWorker
 * Method:    pausedEditorWorker
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_android_video_worker_EFEditorWorker_pausedEditorWorker
  (JNIEnv *, jobject);

/*
 * Class:     com_android_video_worker_EFEditorWorker
 * Method:    resumeEditorWorker
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_android_video_worker_EFEditorWorker_resumeEditorWorker
  (JNIEnv *, jobject);

/*
 * Class:     com_android_video_worker_EFEditorWorker
 * Method:    pauseLoopAnimation
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_android_video_worker_EFEditorWorker_pauseLoopAnimation
  (JNIEnv *, jobject);

/*
 * Class:     com_android_video_worker_EFEditorWorker
 * Method:    resumeLoopAnimation
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_android_video_worker_EFEditorWorker_resumeLoopAnimation
  (JNIEnv *, jobject);

/*
 * Class:     com_android_video_worker_EFEditorWorker
 * Method:    setPlayerProgress
 * Signature: (Lcom/android/video/worker/EFRecordWorker/EFPlayerWorkerProgress;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_android_video_worker_EFEditorWorker_setPlayerProgress
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_android_video_worker_EFEditorWorker
 * Method:    setEditorProgress
 * Signature: (Lcom/android/video/worker/EFRecordWorker/EFEditorWorkerProgress;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_android_video_worker_EFEditorWorker_setEditorProgress
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_android_video_worker_EFEditorWorker
 * Method:    startPlayVideo
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_android_video_worker_EFEditorWorker_loadVideoPlayer
  (JNIEnv *, jobject);

/*
 * Class:     com_android_video_worker_EFEditorWorker
 * Method:    startPlayVideo
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_android_video_worker_EFEditorWorker_unloadVideoPlayer
  (JNIEnv *, jobject);

/*
 * Class:     com_android_video_worker_EFEditorWorker
 * Method:    startPlayVideo
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_android_video_worker_EFEditorWorker_startPlayVideo
  (JNIEnv *, jobject);

/*
 * Class:     com_android_video_worker_EFEditorWorker
 * Method:    pausePlayVideo
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_android_video_worker_EFEditorWorker_pausePlayVideo
  (JNIEnv *, jobject);

/*
 * Class:     com_android_video_worker_EFEditorWorker
 * Method:    stopPlayVideo
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_android_video_worker_EFEditorWorker_stopPlayVideo
  (JNIEnv *, jobject);

/*
 * Class:     com_android_video_worker_EFEditorWorker
 * Method:    restartPlayVideo
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_android_video_worker_EFEditorWorker_restartPlayVideo
  (JNIEnv *, jobject);

/*
 * Class:     com_android_video_worker_EFEditorWorker
 * Method:    renderEffectVideo
 * Signature: (Lcom/android/video/worker/EFRecordWorker/EFRenderWorkerProgress;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_android_video_worker_EFEditorWorker_renderEffectVideo
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_android_video_worker_EFEditorWorker
 * Method:    renderFinishVideo
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_android_video_worker_EFEditorWorker_renderFinishVideo
  (JNIEnv *, jobject);

/*
 * Class:     com_android_video_worker_EFEditorWorker
 * Method:    syncEffectDatas
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_android_video_worker_EFEditorWorker_syncEffectDatas
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_android_video_worker_EFEditorWorker
 * Method:    seekPlayPosition
 * Signature: (F)Z
 */
JNIEXPORT jboolean JNICALL Java_com_android_video_worker_EFEditorWorker_seekPlayPosition
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     com_android_video_worker_EFEditorWorker
 * Method:    extractSerialImages
 * Signature: (IIILcom/android/video/worker/EFRecordWorker/EFExtractWorkerProgress;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_android_video_worker_EFEditorWorker_extractSerialImages
  (JNIEnv *, jobject, jint, jint, jint, jobject);

/*
 * Class:     com_android_video_worker_EFEditorWorker
 * Method:    cleanCocos2dXCaches
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_android_video_worker_EFEditorWorker_cleanCocos2dXCache
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif


#define EDITOR_WORKER_TOUCH_DOWN     1
#define EDITOR_WORKER_TOUCH_MOVE     2
#define EDITOR_WORKER_TOUCH_UP       3

typedef union tag_EFTouchType64 {
	struct {
		float x ;
		float y ;
	};
	uint64_t v ;

	tag_EFTouchType64(float vx, float vy)
	{
		x = vx ;
		y = vy ;
	}
	tag_EFTouchType64(uint64_t vv)
	{
		v = vv ;
	}
} EFTouchType64 ;


#include "NXSDK.h"
#include "EFEffectsLayer.h"
#include "EFEffectsModel.h"

#include "EFRenderMission.h"
#include "EFExtractMission.h"


class EFPlayerProgress ;
class EFEditorProgress ;
class EFRenderProgress ;

class EFEditorWorker : public NXObject
					 , public NXSDKPlayerListener
					 , public EFEffectsListener
{
private:
	NXPtr<NXGLSurface> 			_drawSurface ;
	std::string					_rootsPath   ;
	std::string					_videoFile   ;
	std::string					_rendrPath   ;

	NXSDKMediaFormat			_mediaFormat  ;

	NXPtr<NXSDKPlayer>			_playerPlayer ;
	uint32_t					_playerIndex  ;
	NXPtr<NXBuffer>				_playerImage  ;
	NXPtr<EFPlayerProgress>		_playerProgrs ;

	NXCCSpriteNV12* 			_effectCanvas ;
	EFEffectsLayer*				_effectLayers ;
	NXPtr<EFEditorProgress>		_effectLister ;

	//render
	NXPtr<EFRenderMission>		_renderMisson ;
	NXPtr<EFRenderProgress>		_renderProgrs ;

public:
	EFEditorWorker() ;
	virtual ~EFEditorWorker();
public:
	bool createEditorWorker(ANativeWindow* surface, const char* rootpath, const char* videofile) ;
	bool updateTouchEvent(int type, float x, float y);
	bool destoryEditorWorker() ;

	bool pausedEditorWorker() ;
	bool resumeEditorWorker() ;

	bool pauseLoopAnimation() ;
	bool resumeLoopAnimation() ;

	bool setPlayerProgress(JNIEnv* env, jobject progress) ;
	bool setEditorProgress(JNIEnv* env, jobject progress) ;

	bool loadVideoPlayer();
	bool unloadVideoPlayer();

	bool startPlayVideo();
	bool pausePlayVideo();
	bool stopPlayVideo() ;
	bool restartPlayVideo();

	bool renderEffectVideo(JNIEnv* env, jobject progress);
	bool renderFinishVideo();

	bool syncEffectDatas(const char* effects);
	bool seekPlayPosition(float position) ;
	bool extractSerialImages(int count, int width, int height, JNIEnv* env, jobject progress) ;

	bool cleanCocos2dXCache();

public:
	void on_create_worker(NXPtr<NXObject>& param1, NXPtr<NXObject>& param2, void* param3, uint32_t param4, uint64_t param5, double param6) ;
	void on_update_touch(NXPtr<NXObject>& param1, NXPtr<NXObject>& param2, void* param3, uint32_t param4, uint64_t param5, double param6) ;
	void on_destory_worker(NXPtr<NXObject>& param1, NXPtr<NXObject>& param2, void* param3, uint32_t param4, uint64_t param5, double param6) ;

	void on_pause_worker(NXPtr<NXObject>& param1, NXPtr<NXObject>& param2, void* param3, uint32_t param4, uint64_t param5, double param6) ;
	void on_resume_worker(NXPtr<NXObject>& param1, NXPtr<NXObject>& param2, void* param3, uint32_t param4, uint64_t param5, double param6) ;

	void on_pause_animation(NXPtr<NXObject>& param1, NXPtr<NXObject>& param2, void* param3, uint32_t param4, uint64_t param5, double param6) ;
	void on_resume_animation(NXPtr<NXObject>& param1, NXPtr<NXObject>& param2, void* param3, uint32_t param4, uint64_t param5, double param6) ;

	void on_player_progress(NXPtr<NXObject>& param1, NXPtr<NXObject>& param2, void* param3, uint32_t param4, uint64_t param5, double param6) ;
	void on_editor_progress(NXPtr<NXObject>& param1, NXPtr<NXObject>& param2, void* param3, uint32_t param4, uint64_t param5, double param6) ;

	void on_doload_video(NXPtr<NXObject>& param1, NXPtr<NXObject>& param2, void* param3, uint32_t param4, uint64_t param5, double param6) ;
	void on_unload_video(NXPtr<NXObject>& param1, NXPtr<NXObject>& param2, void* param3, uint32_t param4, uint64_t param5, double param6) ;

	void on_start_playing(NXPtr<NXObject>& param1, NXPtr<NXObject>& param2, void* param3, uint32_t param4, uint64_t param5, double param6) ;
	void on_pause_playing(NXPtr<NXObject>& param1, NXPtr<NXObject>& param2, void* param3, uint32_t param4, uint64_t param5, double param6) ;
	void on_stopd_playing(NXPtr<NXObject>& param1, NXPtr<NXObject>& param2, void* param3, uint32_t param4, uint64_t param5, double param6) ;
	void on_restart_playing(NXPtr<NXObject>& param1, NXPtr<NXObject>& param2, void* param3, uint32_t param4, uint64_t param5, double param6) ;

	void on_render_video(NXPtr<NXObject>& param1, NXPtr<NXObject>& param2, void* param3, uint32_t param4, uint64_t param5, double param6) ;
	void on_render_finsh(NXPtr<NXObject>& param1, NXPtr<NXObject>& param2, void* param3, uint32_t param4, uint64_t param5, double param6) ;

	void on_sync_effects(NXPtr<NXObject>& param1, NXPtr<NXObject>& param2, void* param3, uint32_t param4, uint64_t param5, double param6) ;
	void on_seek_position(NXPtr<NXObject>& param1, NXPtr<NXObject>& param2, void* param3, uint32_t param4, uint64_t param5, double param6) ;
	void on_exct_selimages(NXPtr<NXObject>& param1, NXPtr<NXObject>& param2, void* param3, uint32_t param4, uint64_t param5, double param6) ;

	void on_clean_cc2dcache(NXPtr<NXObject>& param1, NXPtr<NXObject>& param2, void* param3, uint32_t param4, uint64_t param5, double param6) ;

public:
	void create_edit_element() ;
	void destory_edit_element() ;

public:
	virtual void playerLoadCompleted(NXSDKPlayer* player, float duration) ;
	virtual void playerStatusChanged(NXSDKPlayer* player, NXSDKPlayerStatus status) ;
	virtual void playerPlayingProgess(NXSDKPlayer* player,NXPtr<NXBuffer>& vbuffer, float currentTime) ;
	virtual void playerErrorGenerated(NXSDKPlayer* player, uint32_t errorCode) ;

	virtual void onTouchEffectClose(EFEffectsLayer* effectLayer, uint32_t effectKey) ;
};


#define WORKBEACH_EDITORWORK_MESSAGE_CREATEWORKER		0x3001
#define WORKBEACH_EDITORWORK_MESSAGE_TOUCHEVENT			0x3002
#define WORKBEACH_EDITORWORK_MESSAGE_DESTORYWORKER		0x3003

#define WORKBEACH_EDITORWORK_MESSAGE_PAUSEDWORKER		0x3004
#define WORKBEACH_EDITORWORK_MESSAGE_RESUMEWORKER		0x3005

#define WORKBEACH_EDITORWORK_MESSAGE_PAUSEDANIMTN		0x3101
#define WORKBEACH_EDITORWORK_MESSAGE_RESUMEANIMTN		0x3102

#define WORKBEACH_EDITORWORK_MESSAGE_SETPLAYPROGS		0x3103
#define WORKBEACH_EDITORWORK_MESSAGE_SETEDITPROGS		0x3104

#define WORKBEACH_EDITORWORK_MESSAGE_DOLOADVIDEO		0x3105
#define WORKBEACH_EDITORWORK_MESSAGE_UNLOADVIDEO		0x3106

#define WORKBEACH_EDITORWORK_MESSAGE_STARTPLAYER		0x3201
#define WORKBEACH_EDITORWORK_MESSAGE_PAUSEPLAYER		0x3202
#define WORKBEACH_EDITORWORK_MESSAGE_STOPDPLAYER		0x3203
#define WORKBEACH_EDITORWORK_MESSAGE_RSTRTPLAYER		0x3204

#define WORKBEACH_EDITORWORK_MESSAGE_RENDERVIDEO		0x3301
#define WORKBEACH_EDITORWORK_MESSAGE_RENDERFINSH		0x3302

#define WORKBEACH_EDITORWORK_MESSAGE_SYNCEFFECTS		0x3303
#define WORKBEACH_EDITORWORK_MESSAGE_SEEKPOSITON		0x3304
#define WORKBEACH_EDITORWORK_MESSAGE_EXTRACTIMAGES		0x3305

#define WORKBEACH_EDITORWORK_MESSAGE_CLEANCC2DCACHE		0x3401


class EFPlayerProgress : public NXObject
{
private:
	jobject			_globalObject ;
public:
	EFPlayerProgress(jobject progress) ;
	virtual ~EFPlayerProgress() ;
public:
	void onPlayerLoadedCompleted(float duration);
	void onPlayerPlayingProgress(float progress) ;
	void onPlayerPlayingStart() ;
	void onPlayerPlayingPause() ;
	void onPlayerPlayingStoped() ;
};

class EFEditorProgress : public NXObject
{
private:
	jobject			_globalObject ;
public:
	EFEditorProgress(jobject progress) ;
	virtual ~EFEditorProgress() ;
public:
	void onDeleteEffectItem(int effectKey);
};

class EFRenderProgress : public NXObject
{
private:
	jobject			_globalObject ;
public:
	EFRenderProgress(jobject progress) ;
	virtual ~EFRenderProgress() ;
public:
	void onRenderProgressBegin();
	void onRenderProgressProgress(float progress); //0.0-1.0
	void onRenderProgressFailure();
	void onRenderProgressComplete(const char* buildFile);
};

class EFExtractProgress : public NXObject
{
private:
	jobject			_globalObject ;
public:
	EFExtractProgress(jobject progress) ;
	virtual ~EFExtractProgress() ;
public:
	void onExtractImagesStart(int count, int width, int height) ;
	void onExtractImagesIndex(int index, int width, int height, NXPtr<NXBuffer>& image) ;
	void onExtractImagesStop() ;
};

#endif
